version: "2"
checks:
  argument-count:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true

engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true

exclude_patterns:
  - "node_modules/**"
  - "test/**"
  - "config/**"

ratings:
  paths:
    - "**/*.js"
