version: '3.8'

services:
  app:
    image: jashan:1.0
    ports:
      - "8081:8080"  
    environment:
      - ENV=staging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge